[37ddbbe5535cb6c27b8a026b2f28d64319b9f802]
ac = "libs"
ac_section = "04-filenames_plain2"
ac_pattern = "lib/"

[8bff95f3ce0396ff40b4f7d943ea856ac3f846c3]
ac = "libs"
ac_section = "04-filenames_plain2"
ac_pattern = "lib/"

[42210fe8dcd4684a45e0e4db1b8194e291dc8fda]
ac = "libs"
ac_section = "04-filenames_plain2"
ac_pattern = "lib/"

[2904edaf2f09934142f9f6a6d2886879395145cc]
ac = "kernel"
ac_section = "04-filenames_plain2"
ac_pattern = "sys/"

[14bd57d0a78dcd98449597fd3e19749799e36935]
ac = "doc"
ac_section = "02-filenames_wildcards"
ac_pattern = ".*\\.[1-9]"

[543c86636f73119fa1dab860f07396df5a1884d4]
ac = "tests"
ac_section = "02b-filenames_wildcards2"
ac_pattern = "tests\\/.*"

[54b52f655e0fdaef21c3cde85e8bf030efa7b86e]
ac = "kernel"
ac_section = "04-filenames_plain2"
ac_pattern = "sys/"

[3ef25acf3600fb822bdf1487036184b4978d737f]
ac = "build"
ac_section = "03-filenames_plain1"
ac_pattern = "tools/build/"

[5685c07b5a8e4ccc19140eeaa5987a38dca7c668]
ac = "libs"
ac_section = "04-filenames_plain2"
ac_pattern = "lib/"

[874cdf6af695c42d561647f7165c99c2d3df0faa]
ac = "libs"
ac_section = "05-summary-prefix"
ac_pattern = "exterr:"

[3088263177da2813dd09364171feadd0e31d1fc3]
ac = "doc"
ac_section = "02-filenames_wildcards"
ac_pattern = ".*\\.[1-9]"

[b6672803a1cf10dd1c912fe6571a8d426b8868bd]
ac = "build"
ac_section = "02-filenames_wildcards"
ac_pattern = ".*Makefile"

[32ea8209825af594cbfa1fc654d45eb9a6aab528]
ac = "kernel"
ac_section = "04-filenames_plain2"
ac_pattern = "sys/"
g = "LinuxKPI-00"

[9cf85457b13bc7aa125388d63c82acf2b21e9e9e]
ac = "kernel"
ac_section = "04-filenames_plain2"
ac_pattern = "sys/"
g = "LinuxKPI-00"

[f0395993e1ea83705e0da6623843e7d5d03f7269]
ac = "kernel"
ac_section = "04-filenames_plain2"
ac_pattern = "sys/"
g = "LinuxKPI-00"

[8494be1b5af7fe4f765532f802ac0a145e061d73]
ac = "kernel"
ac_section = "04-filenames_plain2"
ac_pattern = "sys/"
g = "LinuxKPI-00"

[faff7013187b03f4240af6f52f608e7ebafe19f3]
ac = "libs"
ac_section = "04-filenames_plain2"
ac_pattern = "lib/"

[85f499be90c15a3de02d1c62ce03b99fab52f925]
ac = "hardware"
ac_section = "03-filenames_plain1"
ac_pattern = "sys/dev/"

[daef625cf884dea33d50ad7a0e2da0879a442495]
ac = "admin"
ac_section = "04-filenames_plain2"
ac_pattern = "usr.sbin/"

[6ea05372bea5bdb19ca329c27c4c6510cbeed7c8]
ac = "build"
ac_section = "02-filenames_wildcards"
ac_pattern = ".*Makefile"

[3e2093de47251de5e6e61c08d2955251137afd01]
ac = "build"
ac_section = "02-filenames_wildcards"
ac_pattern = ".*Makefile"

[04a664d87607d25d87baf56903090707cc91e2e0]
ac = "build"
ac_section = "02-filenames_wildcards"
ac_pattern = ".*Makefile"

[b8c99e7d912f0dad84cec80f8c4331646b87a3ec]
ac = "libs"
ac_section = "05-summary-prefix"
ac_pattern = "lib.*:"
ah = 1

[b0d4b059cf8425cbe094f93362a61c56a26d45f3]
ac = "build"
ac_section = "02-filenames_wildcards"
ac_pattern = ".*Makefile"

[3204c097fd08436805f059c0d7f676d29ee9bb62]
ac = "tests"
ac_section = "03-filenames_plain1"
ac_pattern = "lib/libc/tests/"

[c4bd487da73a28887f86750a5dc5832303592c5a]
ac = "doc"
ac_section = "02-filenames_wildcards"
ac_pattern = ".*\\.[1-9]"

[c6bd2aa8353c6c34dbff487132a7f7372752d0ad]
ac = "doc"
ac_section = "02-filenames_wildcards"
ac_pattern = ".*\\.[1-9]"

[e2afbc45258f2fa4bdcf126e959ac660e76fc802]
ac = "doc"
ac_section = "02-filenames_wildcards"
ac_pattern = ".*\\.[1-9]"
