[d81fe0b206325b40e13625f5684ec8d19fdccf04]
ac = "style"
ac_section = "01-style"
ac_pattern = "[tT]ypo"

[2f263badccf842470323b64613eccb0c0b9a12c1]
ac = "style"
ac_section = "01-style"
ac_pattern = "[tT]ypo"

[3ceaf4d80401fab49895a5ac3bb1fe602f588da8]
ac = "style"
ac_section = "01-style"
ac_pattern = "[tT]ypo"

[5215760811a5ce75d77f9017e392445014e6b1bb]
ac = "style"
ac_section = "01-style"
ac_pattern = "[tT]ypo"

[ad7bbe691b453039980df729f32fffaf02ffd21c]
ac = "style"
ac_section = "01-style"
ac_pattern = "[tT]ypo"

[a1e76a3af8d64b400100d8ab595eeb32cd79d358]
ac = "style"
ac_section = "01-style"
ac_pattern = "[tT]ypo"

[e17c87d4a27509ed8324e69056b06dec878db064]
ac = "style"
ac_section = "01-style"
ac_pattern = "[tT]ypo"

[1a28455cb5f59de98cd6085fce500b457eb80847]
ac = "style"
ac_section = "01-style"
ac_pattern = "[tT]ypo"

[187a0a85e15377405068663af743b78481e5564f]
ac = "style"
ac_section = "01-style"
ac_pattern = "[tT]ypo"

[576e735efb85cae5213621981ed33ced8878a352]
ac = "style"
ac_section = "01-style"
ac_pattern = "[tT]ypo"

[73a78c2dc99a3942d8e503c62537d2f3838a6954]
ac = "style"
ac_section = "01-style"
ac_pattern = "[tT]ypo"

[005603cd3dee7610587f1193f9529eb2a42781d7]
ac = "style"
ac_section = "01-style"
ac_pattern = "[tT]ypo"

[b1f96b1c4c95df5c04e067c638e52c9652f86721]
ac = "style"
ac_section = "01-style"
ac_pattern = "[tT]ypo"

[a859a5c6978de121efc7771351d32550ee430b7c]
ac = "style"
ac_section = "01-style"
ac_pattern = "[tT]ypo"

[40fae644ba9a27227ca6f7c290e54fcef462b341]
ac = "style"
ac_section = "01-style"
ac_pattern = "[tT]ypo"

[fe45f7ddb53f16198a60cd015c20f5fc524aed89]
ac = "style"
ac_section = "01-style"
ac_pattern = "[tT]ypo"

[8eedabfe9ac8b5841662d342c5ba8cbb0ac6e0c5]
ac = "style"
ac_section = "01-style"
ac_pattern = "[tT]ypo"

[3b79697040a7d3f9a4a21fb2e66d9031feb6af84]
ac = "style"
ac_section = "01-style"
ac_pattern = "[tT]ypo"

[364864ea91abbd8a9a79578168fa5d34e05200a7]
ac = "hardware"
ac_section = "03-filenames_plain1"
ac_pattern = "sys/dev/"

[fddf48eb012c8c7dd640c1fea5c0766f8d85f0c4]
ac = "hardware"
ac_section = "03-filenames_plain1"
ac_pattern = "sys/arm64/"

[aa22b68ec76699527de04c99425716ab45c9b8c2]
ac = "hardware"
ac_section = "03-filenames_plain1"
ac_pattern = "sys/arm64/"
g = "arm64-00"

[f3ee178be2b2b4205a42d514db1142d6bf162601]
ac = "hardware"
ac_section = "03-filenames_plain1"
ac_pattern = "sys/arm64/"
g = "arm64-00"

[b57a571a001958febec042e15c571c5074ce44ce]
ac = "hardware"
ac_section = "03-filenames_plain1"
ac_pattern = "sys/arm64/"
g = "arm64-00"

[95a5bfcee07cf522edab72388decc4d6e27d341d]
ac = "hardware"
ac_section = "03-filenames_plain1"
ac_pattern = "sys/arm64/"
g = "arm64-00"

[87cea227e1945a8aa808b72d210f9a391be9b234]
ac = "hardware"
ac_section = "03-filenames_plain1"
ac_pattern = "sys/dev/"

[d539f2d9d2ce88f295567578d0e7a3b49d45544b]
ac = "hardware"
ac_section = "03-filenames_plain1"
ac_pattern = "sys/dev/"

[a505b80b2f038409300cd05e2ea95822942404e2]
ac = "network"
ac_section = "03-filenames_plain1"
ac_pattern = "sys/netgraph/"

[1aad95345237424918e5f6b18464df4dbc2aa1d8]
ac = "admin"
ac_section = "04-filenames_plain2"
ac_pattern = "usr.sbin/"

[ce6792d3cd798079f0c9ba244faba4ea666bb6f4]
ac = "reverts"
ac_section = "00-reverts"
ac_pattern = "This reverts commit \\b([0-9a-fA-F]{40})\\b"
g = "revert-pair-isa-00"

[498e56142660c8dd864c878e820252358c9a15cf]
ac = "admin"
ac_section = "03-filenames_plain1"
ac_pattern = "sbin/"

[34ffc7073f1786bae5e77593abd423ed31c10024]
ac = "contrib"
ac_section = "03-filenames_plain1"
ac_pattern = "contrib/"

[09b48f811b4bf3a17485680b4720d1c0a81bbe07]
ac = "hardware"
ac_section = "03-filenames_plain1"
ac_pattern = "sys/dev/"

[23b46b2bbf0a8f3a740b6e5baf0767816afc339e]
ac = "kernel"
ac_section = "04-filenames_plain2"
ac_pattern = "sys/"

[1a679fb907962843f01b103ec672136a8f8d8edb]
ac = "filesystems"
ac_section = "03-filenames_plain1"
ac_pattern = "sys/fs/"

[cb38499303621553c977fd7dd7f18d12731fcd9c]
ac = "hardware"
ac_section = "03-filenames_plain1"
ac_pattern = "sys/x86/"

[190d0a96cf5672c6cf0ce86eb91dd1f19d35baac]
ac = "kernel"
ac_section = "04-filenames_plain2"
ac_pattern = "sys/"

[e02c57ff374ea3eed69e5f43f19a41fa559b7e2d]
ac = "kernel"
ac_section = "04-filenames_plain2"
ac_pattern = "sys/"

[efd00c75f459752e54e219fc47b18ee6631a7877]
ac = "kernel"
ac_section = "05-summary-prefix"
ac_pattern = "sysent:"

[1ae25866767d686067fe6678b62681b7a8f0d361]
ac = "hardware"
ac_section = "03-filenames_plain1"
ac_pattern = ["sys/arm64/", "sys/dev/"]

[16db4c6fff450d3dd802b6c4b23cae0a8af44976]
ac = "hardware"
ac_section = "03-filenames_plain1"
ac_pattern = ["sys/amd64/", "sys/x86/"]

[3b9578059cce3bc193be651546e191d0177df7d4]
ac = "hardware"
ac_section = "03-filenames_plain1"
ac_pattern = ["sys/arm/", "sys/i386/", "sys/powerpc/", "sys/riscv/"]

[3053b2a3dcab6e05311c3b696bee4c9e5698d93a]
ac = "filesystems"
ac_section = "03-filenames_plain1"
ac_pattern = "sys/fs/"
g = "nfs_clrpcops.c-00"

[b9e6206f593385c80436d267ab759319c1e94e43]
ac = "filesystems"
ac_section = "03-filenames_plain1"
ac_pattern = "sys/fs/"
g = "nfs_clrpcops.c-00"

[2c82cdd2e29f8ba00d4289f36f8baa1598a1ad9b]
ac = "filesystems"
ac_section = "03-filenames_plain1"
ac_pattern = "sys/fs/"
g = "nfs_clrpcops.c-00"

[b502a451cbae6a85636c7b8375f5ee53caca4388]
ac = "contrib"
ac_section = "03-filenames_plain1"
ac_pattern = "contrib/"

[79e374217d69a98161fc91a286dacf1f78090894]
ac = "admin"
ac_section = "03-filenames_plain1"
ac_pattern = "libexec/"

[0e2e0fb955adf15a217949bc4cc337d53d2c7259]
ac = "admin"
ac_section = "03-filenames_plain1"
ac_pattern = "sbin/"

[32919a34f17ac1af99dec7376f22a8393c251602]
ac = "network"
ac_section = "03-filenames_plain1"
ac_pattern = "sys/net/"

[ff08916e9ac689e6ce734de72325fc2bd9495a35]
ac = "network"
ac_section = "03-filenames_plain1"
ac_pattern = "sys/net/"

[500717311bff635dac12602a27d0dbca02cf9a2e]
ac = "network"
ac_section = "03-filenames_plain1"
ac_pattern = "sys/net/"

[ef7b81340b8e0ad06584f364aa02105c03ca5f7c]
ac = "kernel"
ac_section = "04-filenames_plain2"
ac_pattern = "sys/"

[d5d47e1e67cdf1707cb460c2722894305f3cb34d]
ac = "kernel"
ac_section = "04-filenames_plain2"
ac_pattern = "sys/"

[2fbb6e213ac2075594da5f68a72d41074fd85b69]
ac = "tests"
ac_section = "02b-filenames_wildcards2"
ac_pattern = "tests\\/.*"

[34dfccc64f47f1549e65593b4a3aa8d31757529d]
ac = "hardware"
ac_section = "03-filenames_plain1"
ac_pattern = "sys/dev/"

[3bcd7d4fa46a29ec3576d9474e9541510885cfaf]
ac = "doc"
ac_section = "02-filenames_wildcards"
ac_pattern = ".*\\.[1-9]"

[d86025c1d49c84c4dc8c3635c83c078ad56e5a53]
ac = "tests"
ac_section = "02b-filenames_wildcards2"
ac_pattern = "tests\\/.*"

[514fff24b19f69c5f22db380389128eb6bc32ea7]
ac = "doc"
ac_section = "02-filenames_wildcards"
ac_pattern = ".*\\.[1-9]"

[c59aab9a5b3970b3ccec744f759e6cb87e938dbe]
ac = "network"
ac_section = "03-filenames_plain1"
ac_pattern = ["sys/netinet/", "sys/netpfil/"]

[8a25a04058a81453108e7e6accbf6663c19e9117]
ac = "hardware"
ac_section = "03-filenames_plain1"
ac_pattern = "sys/dev/"

[44cb1e857f048d2326bdc1a032ccd2c04d2bcdc9]
ac = "network"
ac_section = "03-filenames_plain1"
ac_pattern = "sys/netinet/"

[5ae7b106cfd4801ef5e0f69b02ad9b3ae3ccfbec]
ac = "style"
ac_section = "01-style"
ac_pattern = "[tT]ypo"

[b87836e824ea40793317d551eb13a8e2814f83f9]
ac = "style"
ac_section = "01-style"
ac_pattern = "[tT]ypo"

[1ef6fef9d5c82a106ba8e42c1e087f9b5d1dfec6]
ac = "style"
ac_section = "01-style"
ac_pattern = "[tT]ypo"

[aa0cd9e5b4d21b11097e1c21a3c0eb23525c15c3]
ac = "style"
ac_section = "01-style"
ac_pattern = "[tT]ypo"

[e9058e1444d8e5831a237934ca2316e22fc55f36]
ac = "style"
ac_section = "01-style"
ac_pattern = "[tT]ypo"

[b57198f620bcbf899a32c3de9526bd525ab8a39e]
ac = "style"
ac_section = "01-style"
ac_pattern = "[tT]ypo"

[74dfef71d8c0f55ebe09337eabd797e03dc0ef1a]
ac = "build"
ac_section = "02-filenames_wildcards"
ac_pattern = ".*Makefile"

[90cd623611b22e2e484b800743845b38d9c20250]
ac = "hardware"
ac_section = "03-filenames_plain1"
ac_pattern = "share/misc/usb_vendors"

[e5f545e0d872fbfdb6c3c94ca81e7f3bce9d094a]
ac = "hardware"
ac_section = "03-filenames_plain1"
ac_pattern = "share/misc/pci_vendors"

[a943a96a50ba7e9d1e1935bdd18df0e11d158acb]
ac = "libs"
ac_section = "04-filenames_plain2"
ac_pattern = "lib/"

[99560fe98c76371d7f0807c2088c78790ca9f943]
ac = "admin"
ac_section = "03-filenames_plain1"
ac_pattern = "sbin/"

[6f0942bde7a08fe46e575486f0e9c97c055d5aad]
ac = "reverts"
ac_section = "00-reverts"
ac_pattern = "This reverts commit \\b([0-9a-fA-F]{40})\\b"

[e12ec5f4338c2d769c266278320232a98a962f63]
ac = "reverts"
ac_section = "00-reverts"
ac_pattern = "This reverts commit \\b([0-9a-fA-F]{40})\\b"

[3d73146baeb933fe955c7496572b483a9f92914c]
ac = "userland"
ac_section = "03-filenames_plain1"
ac_pattern = "bin/"

[22cff1f3e9d82b48aad440c52f883bfd4995359c]
ac = "admin"
ac_section = "03-filenames_plain1"
ac_pattern = "libexec/"

[b0cfcd07bb6134ebe319c57142be2b53bb9090e7]
ac = "reverts"
ac_section = "00-reverts"
ac_pattern = "This reverts commit \\b([0-9a-fA-F]{40})\\b"
g = "revert-pair-isa-00"

[24a6e040fc2e84234c684abcf3e1668a5a9467eb]
ac = "doc"
ac_section = "02-filenames_wildcards"
ac_pattern = ".*\\.[1-9]"

[cadadd1a0398fdeaebf62ab4d092ada0e3eb68c8]
ac = "doc"
ac_section = "02-filenames_wildcards"
ac_pattern = ".*\\.[1-9]"

[0cd8754ad52bb8174b8a766708424a4c53b8fc96]
ac = "doc"
ac_section = "02-filenames_wildcards"
ac_pattern = ".*\\.[1-9]"

[9447a4078121fd1ce961fed33dd0099040d0dac9]
ac = "admin"
ac_section = "03-filenames_plain1"
ac_pattern = "sbin/"

[4672adcea4cf3c0c626d186f1f41c69552d915f1]
ac = "filesystems"
ac_section = "03-filenames_plain1"
ac_pattern = "sys/fs/"

[70b72ede982f3aebe03a2bf7a8245ee6bcde352c]
ac = "userland"
ac_section = "04-filenames_plain2"
ac_pattern = "usr.bin/"

[f41b1eb637f576634be0df9d657f46aa57afea59]
ac = "userland"
ac_section = "04-filenames_plain2"
ac_pattern = "usr.bin/"

[b2c5686755757535a6c3223b31fb96b64a961f15]
ac = "doc"
ac_section = "02-filenames_wildcards"
ac_pattern = ".*\\.[1-9]"

[c6e12d38f167d4cea1e8bb8119f4677c1c008c6a]
ac = "hardware"
ac_section = "03-filenames_plain1"
ac_pattern = "sys/dev/"

[c6b156e360fc5b18ee20bae0fc0c4188c3aadea6]
ac = "admin"
ac_section = "04-filenames_plain2"
ac_pattern = "usr.sbin/"

[924c0c60d4aeaa474fb028118ca82d505166b4ab]
ac = "build"
ac_section = "02-filenames_wildcards"
ac_pattern = [".*Makefile", "release/.*"]

[20a38e847251076b12c173d7aa0b37eef261fd32]
ac = "hardware"
ac_section = "03-filenames_plain1"
ac_pattern = ["sys/amd64/", "sys/dev/"]

[38b81fbb9c375ef20c56e5d6f4099b88fcdba44c]
ac = "doc"
ac_section = "02-filenames_wildcards"
ac_pattern = ".*\\.[1-9]"

[cb1315c15acf7d3fae66b2c5631e076776683f96]
ac = "doc"
ac_section = "02-filenames_wildcards"
ac_pattern = ".*\\.[1-9]"

[9d13c87afdb35c0014aa6f43c5652e946c18b756]
ac = "filesystems"
ac_section = "03-filenames_plain1"
ac_pattern = "sys/fs/"

[83519c1764f80ddbdf34e16de08ff110226aba2b]
ac = "reverts"
ac_section = "00-reverts"
ac_pattern = "This reverts commit \\b([0-9a-fA-F]{40})\\b"
g = "revert-pair-bus-00"

[471743e1315cdc54d85e3e77b53e3841b3647ea1]
ac = "hardware"
ac_section = "03-filenames_plain1"
ac_pattern = "sys/dev/"

[86b259a28a1a47b0506c519b17d8adb67d4a0b0d]
ac = "reverts"
ac_section = "00-reverts"
ac_pattern = "This reverts commit \\b([0-9a-fA-F]{40})\\b"
g = "revert-pair-bus-00"

[685a78570b359eb2bd4d8c28dde22de54d55b8ec]
ac = "kernel"
ac_section = "05-summary-prefix"
ac_pattern = "random:"
g = "random: remove hifn(4)-00"

[a38a42ed9a9754553212058177093f24a7f48d09]
ac = "build"
ac_section = "02-filenames_wildcards"
ac_pattern = ".*Makefile"
fc = "kernel"
fc_reason = "Need to be grouped with 685a78570b359eb2bd4d8c28dde22de54d55b8ec"
g = "random: remove hifn(4)-00"

[88a53301e198b043e9b046b1c824eae5a24064f9]
ac = "build"
ac_section = "02-filenames_wildcards"
ac_pattern = ".*Makefile"

[73551cd6eac29a6707c802c7d7fafcb560bf5e2b]
ac = "filesystems"
ac_section = "03-filenames_plain1"
ac_pattern = "sys/fs/"

[98edcbcce0a4650084bd86e704cfa38bf590250c]
ac = "libs"
ac_section = "04-filenames_plain2"
ac_pattern = "lib/"

[4b6700f3455f46aaed2c090e1c67c67565f26369]
ac = "doc"
ac_section = "02-filenames_wildcards"
ac_pattern = ".*\\.[1-9]"

[adfe14dcc2747a20dff961044d6817c507087327]
ac = "style"
ac_section = "01-style"
ac_pattern = "[tT]ypo"

[08a6620093dc2786051bf6ae6f40ae048027021b]
ac = "style"
ac_section = "01-style"
ac_pattern = "[tT]ypo"

[d1e39f3d6e5fce1a30a5713d522f87d83654c4bd]
ac = "style"
ac_section = "01-style"
ac_pattern = "[tT]ypo"

[db0d002a217b1171ca85e8c17706de744ab6635d]
ac = "tests"
ac_section = "02b-filenames_wildcards2"
ac_pattern = "tests\\/.*"

[63af953e09ccd11f2f5b4d83b10cc231f691de46]
ac = "style"
ac_section = "01-style"
ac_pattern = "[tT]ypo"

[679976d8162004f879a1a0d5ca0c5d2ade5fa1bd]
ac = "style"
ac_section = "01-style"
ac_pattern = "[tT]ypo"

[57b78a557b3ce07b1589c9c21debe97d45599391]
ac = "style"
ac_section = "01-style"
ac_pattern = "[tT]ypo"

[b074d146969d3097c1e144623360b36083d74927]
ac = "style"
ac_section = "01-style"
ac_pattern = "[tT]ypo"

[862024c00f3126220ac425f9ec1f3d4286064688]
ac = "style"
ac_section = "01-style"
ac_pattern = "[tT]ypo"

[6a02851a0e346cbff074dab87807c9ee9d1e8d94]
ac = "style"
ac_section = "01-style"
ac_pattern = "[tT]ypo"

[f51fb91d616d49e91f3c2c706263a38b98176911]
ac = "style"
ac_section = "01-style"
ac_pattern = "[tT]ypo"

[a675f3bb63774a63f668749c6c3c8dfbb6be1cd6]
ac = "style"
ac_section = "01-style"
ac_pattern = "[tT]ypo"

[d617806aac1469319970e3551656e9deabb98a35]
ac = "libs"
ac_section = "04-filenames_plain2"
ac_pattern = "lib/"

[be27c64b3a0150534252a66263703283a79c39a0]
ac = "internal"
ac_section = "05-summary-prefix"
ac_pattern = "git-arc:"

[2acdec9e4d915ec61d0ca45b408f9beb7aa4b772]
ac = "kernel"
ac_section = "04-filenames_plain2"
ac_pattern = "sys/"

[330b4f470280ec42d1498f875b8873f6eb32a7dd]
ac = "hardware"
ac_section = "03-filenames_plain1"
ac_pattern = "sys/dev/"

[3bbdc0223a7c1efaf734d3d9f3cb818e79e11d54]
ac = "hardware"
ac_section = "03-filenames_plain1"
ac_pattern = "sys/dev/"
