# The git repository's "commit dates" are not always accurate, so we
# cannot rely on dates for the bounds of each span.  The "date_start" and
# "date_end" are purely for display; the actual spans are defined by
# "start_after" and "end_including".
#
# I'm not wild about "start_after" and "end_including" -- I think it would
# be more natural to have "start_including" and "end_before" -- but that's
# what `git rev-list A..B` does.  As long as the names reflect what the
# system does, it's fine.

[2025-09-01]
display_date_start = "2025-09-01"
display_date_end = "2025-09-07"
start_after = "004ce88ad1efd42a1d7d5692849b4aa6906178fc"
end_including = "14b61b2e931741281d0bfef426e9809f16006504"

[2025-09-08]
display_date_start = "2025-09-08"
display_date_end = "2025-09-14"
start_after = "14b61b2e931741281d0bfef426e9809f16006504"
end_including = "e779891327b1d9b9ab10ba482e59f498790505a7"

[2025-09-15]
display_date_start = "2025-09-15"
display_date_end = "2025-09-21"
start_after = "e779891327b1d9b9ab10ba482e59f498790505a7"
end_including = "52c4b76d1dd385fbe33b78172e39a10749b83d13"

[2025-09-22]
display_date_start = "2025-09-22"
display_date_end = "2025-09-28"
start_after = "52c4b76d1dd385fbe33b78172e39a10749b83d13"
end_including = "008d04b297c700ed386a4e846c1834ade7255043"

[2025-09-29]
display_date_start = "2025-09-29"
display_date_end = "2025-10-05"
start_after = "008d04b297c700ed386a4e846c1834ade7255043"
end_including = "4dc4a512e0659c9155db7412d2821bef409b48af"

[2025-10-06]
display_date_start = "2025-10-06"
display_date_end = "2025-10-12"
start_after = "4dc4a512e0659c9155db7412d2821bef409b48af"
end_including = "0cc81b375ea43c7e853b109d00c72c8c3b3df993"

[2025-10-13]
display_date_start = "2025-10-13"
display_date_end = "2025-10-19"
start_after = "0cc81b375ea43c7e853b109d00c72c8c3b3df993"
end_including = "f6d767fe862964f704baf4eb388a30ed8227bb65"

[2025-10-20]
display_date_start = "2025-10-20"
display_date_end = "2025-10-26"
start_after = "f6d767fe862964f704baf4eb388a30ed8227bb65"
end_including = "1d100747d747887a13498216d39b03e26b381d8b"

[2025-10-27]
display_date_start = "2025-10-27"
display_date_end = "2025-11-02"
start_after = "1d100747d747887a13498216d39b03e26b381d8b"
end_including = "088ced14a69ba2dce083c031b60c0d04ba218488"

[2025-11-03]
display_date_start = "2025-11-03"
display_date_end = "2025-11-09"
start_after = "088ced14a69ba2dce083c031b60c0d04ba218488"
end_including = "c3d2b68c6933d0610bc3e09e9b94f963b4dc85aa"

[2025-11-10]
display_date_start = "2025-11-10"
display_date_end = "2025-11-16"
start_after = "c3d2b68c6933d0610bc3e09e9b94f963b4dc85aa"
end_including = "4c736cfc69a7ef81c48c8431b31c7e31746fe816"

[2025-11-17]
display_date_start = "2025-11-17"
display_date_end = "2025-11-23"
start_after = "4c736cfc69a7ef81c48c8431b31c7e31746fe816"
end_including = "3289bace53f31545976fec310b41fa784de75e64"

[2025-11-24]
display_date_start = "2025-11-24"
display_date_end = "2025-11-30"
start_after = "3289bace53f31545976fec310b41fa784de75e64"
end_including = "5bfdb66ad985774b123ecd0cadee65c071b7ded0"

[2025-12-01]
display_date_start = "2025-12-01"
display_date_end = "2025-12-07"
start_after = "5bfdb66ad985774b123ecd0cadee65c071b7ded0"
end_including = "8b78d412aec7f9171ecc2e1cd8aea07b19b4f600"

[2025-12-08]
display_date_start = "2025-12-08"
display_date_end = "2025-12-14"
start_after = "8b78d412aec7f9171ecc2e1cd8aea07b19b4f600"
end_including = "edd982b95372bee56de4bfe3a61873a8fed254ae"

[2025-12-15]
display_date_start = "2025-12-15"
display_date_end = "2025-12-21"
start_after = "edd982b95372bee56de4bfe3a61873a8fed254ae"
end_including = "a35bbd5d9f5f887a6f3de15cfe61fcc73fe22dc8"

[2025-12-22]
display_date_start = "2025-12-22"
display_date_end = "2025-12-28"
start_after = "a35bbd5d9f5f887a6f3de15cfe61fcc73fe22dc8"
end_including = "541a98d7e28a8e4697ac2fa78dd4c4203c2c3a9c"

[2025-12-29]
display_date_start = "2025-12-29"
display_date_end = "2026-01-04"
start_after = "541a98d7e28a8e4697ac2fa78dd4c4203c2c3a9c"
end_including = "9c923575606bbd29dcf0ec3384150d2d67136cbb"

[2026-01-05]
display_date_start = "2026-01-05"
display_date_end = "2026-01-11"
start_after = "9c923575606bbd29dcf0ec3384150d2d67136cbb"
end_including = "e3bfcf6b594e8388c4a2e1835519a8026e90cf71"

[2026-01-12]
display_date_start = "2026-01-12"
display_date_end = "2026-01-18"
start_after = "e3bfcf6b594e8388c4a2e1835519a8026e90cf71"
end_including = "8ac6427b1bb95470f6c755202d1c0391ed8eefbd"

[2026-01-19]
display_date_start = "2026-01-19"
display_date_end = "2026-01-25"
start_after = "8ac6427b1bb95470f6c755202d1c0391ed8eefbd"
end_including = "c0898bdc8661842c51fecfe467a1c921a2d81774"
ongoing = true

[2025-09]
derived = true
display_name = "2025-09, all"
display_date_start = "2025-09-01"
display_date_end = "2025-09-30"
include_spans = [2025-09-01, 2025-09-08, 2025-09-15, 2025-09-22, 2025-09-29]
start_after = "004ce88ad1efd42a1d7d5692849b4aa6906178fc"
end_including = "c2900b6e8255ba4f54dbd897cf42427db577ed3d"

[2025-Q4]
derived = true
display_name = "2025-Q4, all"
display_date_start = "2025-10-01"
display_date_end = "2025-12-31"
include_spans = [
    2025-09-29,
    2025-10-06, 2025-10-13, 2025-10-20, 2025-10-27,
    2025-11-03, 2025-11-10, 2025-11-17, 2025-11-24,
    2025-12-01, 2025-12-08, 2025-12-15, 2025-12-22, 2025-12-29,
]
start_after = "c2900b6e8255ba4f54dbd897cf42427db577ed3d"
end_including = "aa611fa7e835ae77a623cc6d05020f5ee76dc881"

[2026-Q1]
derived = true
display_name = "2026-Q1, all"
display_date_start = "2026-01-01"
display_date_end = "2026-03-31"
include_spans = [
    2025-12-29, 2026-01-05,
]
start_after = "aa611fa7e835ae77a623cc6d05020f5ee76dc881"
end_including = "9c923575606bbd29dcf0ec3384150d2d67136cbb"
ongoing = true
